# nombre del workflow
name:  Instalacion de paquetes usando actions
# marque que evento/s dispararan el workflow
on: [push]

jobs:
  installing-packages:
    # en que corre
    runs-on: ubuntu-latest
    # pasos del job
    steps:
      # conecta al github workspace
      - name: Checkout
        uses: actions/checkout@v5.0.0
      # nombre del paso
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        # parametros que se pasan al action a usar
        with:
          node-version: latest
      - name: node version
        run: node --version
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.35.5
        with: 
          php-version: '8.4'
      - name: php version
        run: php --version