# nombre del workflow
name:  Interdependent jobs
# marque que evento/s dispararan el workflow
on: [push]

jobs:
  # nombre del job
  saludar:
    # en que corre
    runs-on: ubuntu-latest
    # pasos del job
    steps:
      # nombre del paso
      - name: saludar
        # correr comando
        run: echo "Hola mundo"
      - name: touch file
        run: touch hola.txt
      - name: set text
        run: echo "Hola mundo" >> hola.txt
      - name: read file
        run: cat hola.txt
  other:
    # en que corre
    runs-on: ubuntu-latest
    # indica que depende de otro job tambien lo podes definir como array [saludar,...]
    needs: saludar
    # pasos del job
    steps:
      # nombre del paso
      - name: LS
        # correr comando
        run: ls -al
